services:
  db:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
      
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@localhost:5432/mydb
    command: >
      sh -c "python -m scripts.setup_timescaledb &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
